### ISSUE TITLE
Use kibanas color palette

### ISSUE THREAD

**Issue by bgeVam** [bgeVam/kibana_treemap_visualization#2]
Right now d3 category 10 color palette is used ([see here](https://github.com/bgeVam/kibana_treemap_visualization/blob/master/public/treemap_d3.js#L25)). These are not the colors that are used in kibana by default. How do I find out?

**Comment by Mythirion** [comment]
Apologies if you've seen this already, but there's a quantitative color palette here:
https://elastic.github.io/eui/#/utilities/color-palettes

I don't know too much about implementation of it but there's a Javascript example.

**Comment by bgeVam** [comment]
Thank you @Mythirion :)
